<?php
return array(
	'DT_MODEL'         =>'Home',
	'DT_URLTYPE'       =>3,
	'DT_CONTROLLER'    =>'Index',
	'DT_ACTION'        =>'Index',
	'DT_C_NAME'        =>'C',
	'DT_M_NAME'        =>'M',
	'DT_CHARSET'       =>'utf-8',
	'DT_THEME'         =>'default',
	'DT_V_EXT'         =>'.html',
	'DT_V_CACHE'       =>'false',
	'PRJ_CDIR'         =>PRJ.'/C/',
	'PRJ_MDIR'         =>PRJ.'/M/',
	'PRJ_COM'          =>PRJ.'/Com/',
	'PRJ_CONF'         =>PRJ.'/Conf/',
	'PRJ_VDIR'         =>PRJ.'/T/',
	'PRJ_VCDIR'        =>PRJ.'/T_c/',
	'PRJ_VCACHE'       =>PRJ.'/T_cache/',
	'DT_V_LEFT'        =>'{',
	'DT_V_RIGHT'       =>'}',
	'DB_HOST'          =>'localhost',
	'DB_NAME'          =>'speek',
	'DB_USER'          =>'root',
	'DB_PASS'          =>'gentai',
	'DB_PREFIX'        =>'sp_',
	'DB_CHARSET'       =>'UTF-8',
);
?>
